/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ch0psticks_rop_MainActivity */

#ifndef _Included_com_ch0psticks_rop_MainActivity
#define _Included_com_ch0psticks_rop_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ch0psticks_rop_MainActivity
 * Method:    ExecRop
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ch0psticks_rop_MainActivity_ExecRop
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_ch0psticks_rop_MainActivity
 * Method:    TestCommand
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ch0psticks_rop_MainActivity_TestCommand
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
